### ISSUE TITLE
netlink: TestLinuxConnIntegrationConcurrent occasionally fails

### ISSUE THREAD

**Issue by mdlayher** [mdlayher/netlink#39]
After running this command approximately 5 times:

```
[zsh|matt@nerr-2]:~/src/github.com/mdlayher/netlink 0 *(bpf) ± go test -tags=integration ./...
panic: failed to execute request: mismatched sequence in netlink reply

goroutine 75 [running]:
github.com/mdlayher/netlink.TestLinuxConnIntegrationConcurrent.func2(0xc4200e44e0, 0x2710, 0xc4200b6710)
        /home/matt/src/github.com/mdlayher/netlink/conn_linux_test.go:317 +0x2a2
created by github.com/mdlayher/netlink.TestLinuxConnIntegrationConcurrent
        /home/matt/src/github.com/mdlayher/netlink/conn_linux_test.go:351 +0x2f4
FAIL    github.com/mdlayher/netlink     0.115s
?       github.com/mdlayher/netlink/cmd/genllist        [no test files]
?       github.com/mdlayher/netlink/cmd/nl80211demo     [no test files]
?       github.com/mdlayher/netlink/cmd/nlecho  [no test files]
?       github.com/mdlayher/netlink/cmd/nlmcast [no test files]
ok      github.com/mdlayher/netlink/genetlink   0.003s
ok      github.com/mdlayher/netlink/nlenc       0.001s

```

I've seen this in CI a couple times as well.  Will try to get to the bottom of it.

**Comment by mdlayher** [comment]
I dropped the concurrency to 1 for now after experiencing much more frequent failures in Travis.  I plan on reaching out to the `libnl` mailing list to pick their brains about netlink sockets and concurrency.
